apiVersion: batch/v1
kind: Job
metadata:
  name: rag-keycloak-db-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: postgres:16
        command:
        - sh
        - -c
        - |
          until pg_isready -h rag-postgresql -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      containers:
      - name: create-db
        image: postgres:16
        env:
        - name: PGPASSWORD
          value: "postgres"
        command:
        - sh
        - -c
        - |
          psql -h rag-postgresql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'keycloak'" | grep -q 1 || psql -h rag-postgresql -U postgres -c "CREATE DATABASE keycloak"
