apiVersion: v1
data:
  auth: {{ .Values.backend.secrets.basicAuth | b64enc }}
  {{- range $key, $value := .Values.backend.secrets.auth }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: basic-auth
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.mlflowName" . }}
type: Opaque
data:
  MLFLOW_API_TOKEN: {{ .Values.backend.secrets.mlflow.apiToken | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitVllmName" . }}
type: Opaque
data:
  STACKIT_VLLM_API_KEY: {{ .Values.backend.secrets.stackitVllm.apiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.stackitEmbedderName" . }}
type: Opaque
data:
  STACKIT_EMBEDDER_API_KEY: {{ .Values.backend.secrets.stackitEmbedder.apiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.ragasName" . }}
type: Opaque
data:
  RAGAS_OPENAI_API_KEY: {{ .Values.backend.secrets.ragas.openaiApikey | b64enc }}
